alias egrep='egrep --color=auto'
alias fano='sudo nano'
alias fgrep='fgrep --color=auto'
alias fucking='sudo'
alias ga='git commit -a --amend && git push -f'
alias gbr='git branch -r'
alias gc='git checkout master'
alias gl='git checkout -'
alias gm='git checkout master'
alias gp='git pull'
alias grep='grep --color=auto'
alias gs='git status'
alias i='sudo yum -y install '
alias l.='ls -d .* --color=auto'
alias ll='ls -lah'
alias ls='ls --color=auto'
alias sudo='sudo '
alias u="P_UPDATE"
alias vssh="vagrant ssh "
alias vspin="vagrant up && vssh"
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias yum='sudo yum'
alias yumi='sudo yum -y install'
alias yums='yum search'
alias pn="P_NAME"