alias egrep='egrep --color=auto'
alias fano='sudo nano'
alias fgrep='fgrep --color=auto'
alias fucking='sudo'
alias gbr='git branch -r'
alias gc='git checkout master'
alias grep='grep --color=auto'
alias l.='ls -d .* --color=auto'
alias ll='ls -lah'
alias ls='ls --color=auto'
alias sudo="sudo "
alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias yum='sudo yum'
alias yumi='sudo yum -y install'
alias yums='yum search'
