echo Install golang...
P_INSTAL golang || P_INSTAL go

echo Install terraform...
go get github.com/hashicorp/terraform
echo Install Virtualbox Plugin...
go get github.com/ccll/terraform-provider-virtualbox
